# WFC Quality Targets (generated by wfc-init)
.PHONY: quality-check format lint test dev setup-dev dogfood preflight

quality-check: format lint
	@echo "All quality checks passed"

format:
	@echo "Formatting code..."
	@uv run black src/ tests/
	@echo "Code formatted"

lint:
	@echo "Linting..."
	@uv run ruff check src/ tests/
	@echo "Linting complete"

CONTAINER_ENGINE ?= $(shell command -v podman 2>/dev/null || command -v docker 2>/dev/null)

test:
	@$(CONTAINER_ENGINE) build -f Dockerfile.test -t eedom-test:latest .
	@$(CONTAINER_ENGINE) run --rm \
		-v "$(CURDIR):/workspace:ro" \
		-w /workspace \
		-e EEDOM_ALLOW_GLOBAL=1 \
		eedom-test:latest \
		python3 -m pytest tests/ -v

test-host:
	@EEDOM_ALLOW_HOST_TESTS=1 uv run pytest tests/ -v

dev:
	@uv sync --group dev

setup-dev: dev
	@bash scripts/setup-dev.sh

dogfood:
	bash scripts/dogfood.sh

preflight: quality-check test dogfood
	@echo "Preflight complete."
