# WFC Quality Targets (generated by wfc-init)
.PHONY: quality-check format lint test test-build test-amd64 prod-build prod-smoke dev setup-dev dogfood preflight

quality-check: format lint
	@echo "All quality checks passed"

format:
	@echo "Formatting code..."
	@uv run black src/ tests/
	@echo "Code formatted"

lint:
	@echo "Linting..."
	@uv run ruff check src/ tests/
	@echo "Linting complete"

CONTAINER_ENGINE ?= $(shell command -v podman 2>/dev/null || command -v docker 2>/dev/null)
CONTAINER_SECURITY_OPT ?= --security-opt apparmor=unconfined
CONTAINER_COMMAND := $(notdir $(CONTAINER_ENGINE))
TEST_BUILD_COMMAND ?= $(if $(filter docker,$(CONTAINER_COMMAND)),$(CONTAINER_ENGINE) buildx build --allow security.insecure --load,$(CONTAINER_ENGINE) build $(CONTAINER_SECURITY_OPT))
PROD_BUILD_COMMAND ?= $(if $(filter docker,$(CONTAINER_COMMAND)),$(CONTAINER_ENGINE) buildx build --allow security.insecure --load,$(CONTAINER_ENGINE) build $(CONTAINER_SECURITY_OPT))
TEST_PLATFORM ?= linux/amd64
TEST_IMAGE ?= eedom-test:amd64
PROD_PLATFORM ?= linux/amd64
PROD_IMAGE ?= eedom:amd64

test-build:
	@$(TEST_BUILD_COMMAND) --platform $(TEST_PLATFORM) -f Dockerfile.test -t $(TEST_IMAGE) .

test:
	@$(MAKE) test-build
	@$(CONTAINER_ENGINE) run --rm \
		--platform $(TEST_PLATFORM) \
		$(CONTAINER_SECURITY_OPT) \
		$(TEST_IMAGE) \
		python3 -m pytest tests/ -v

test-amd64: test

prod-build:
	@$(PROD_BUILD_COMMAND) --platform $(PROD_PLATFORM) -f Dockerfile -t $(PROD_IMAGE) .

prod-smoke: prod-build
	@$(CONTAINER_ENGINE) run --rm \
		--platform $(PROD_PLATFORM) \
		$(CONTAINER_SECURITY_OPT) \
		--entrypoint eedom \
		$(PROD_IMAGE) \
		--help >/dev/null

test-host:
	@EEDOM_ALLOW_HOST_TESTS=1 uv run pytest tests/ -v

test-e2e:
	@$(CONTAINER_ENGINE) build -t eedom:latest .
	@$(CONTAINER_ENGINE) run --rm \
		-v "$(CURDIR):/workspace:ro" \
		-w /workspace \
		-e EEDOM_E2E=1 \
		-e EEDOM_ALLOW_GLOBAL=1 \
		--entrypoint "" \
		eedom:latest \
		python3 -m pytest tests/e2e/ -v

test-all: test test-e2e

dev:
	@uv sync --group dev

setup-dev: dev
	@bash scripts/setup-dev.sh

dogfood:
	bash scripts/dogfood.sh

preflight: quality-check test dogfood
	@echo "Preflight complete."
