#!/usr/bin/env python3
"""Sync scanner exclusion configs from config/scan-exclusions.toml.

Reads the centralized fixture-dir list and generates:
  - osv-scanner.toml in every lockfile directory under each fixture root
  - Validates that dependabot.yml exclude-paths covers every fixture root

Run after editing config/scan-exclusions.toml:
    uv run scripts/sync_scan_exclusions.py
"""

from __future__ import annotations

import sys
import tomllib
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent
CONFIG_PATH = REPO_ROOT / "config" / "scan-exclusions.toml"
DEPENDABOT_PATH = REPO_ROOT / ".github" / "dependabot.yml"

# osv-scanner recognizes these as lockfiles when scanning recursively
LOCKFILE_NAMES = {
    "requirements.txt",
    "requirements.in",
    "Pipfile.lock",
    "poetry.lock",
    "pyproject.toml",
    "uv.lock",
    "package-lock.json",
    "yarn.lock",
    "pnpm-lock.yaml",
    "Cargo.lock",
    "go.sum",
    "Gemfile.lock",
    "composer.lock",
    "packages.lock.json",
    "paket.lock",
}

OSV_CONFIG_HEADER = """\
# AUTO-GENERATED by scripts/sync_scan_exclusions.py — do not edit manually.
# Source of truth: config/scan-exclusions.toml
#
# Instructs osv-scanner to ignore all packages found in this directory.
# This directory contains intentionally pinned old deps used as scan-target
# fixtures — they are test inputs for eedom, not eedom's own dependencies.

[[PackageOverrides]]
ignore = true
reason = "e2e test fixture — intentionally pinned to old versions for scan testing"
"""


def find_lockfile_dirs(fixture_root: Path) -> list[Path]:
    """Return unique directories that contain at least one lockfile."""
    dirs: set[Path] = set()
    for f in fixture_root.rglob("*"):
        if f.is_file() and f.name in LOCKFILE_NAMES:
            dirs.add(f.parent)
    return sorted(dirs)


def write_osv_configs(fixture_roots: list[Path]) -> list[Path]:
    written: list[Path] = []
    for root in fixture_roots:
        for lockfile_dir in find_lockfile_dirs(root):
            target = lockfile_dir / "osv-scanner.toml"
            target.write_text(OSV_CONFIG_HEADER, encoding="utf-8")
            written.append(target)
            print(f"  wrote {target.relative_to(REPO_ROOT)}")
    return written


def validate_dependabot(fixture_roots: list[Path]) -> list[str]:
    """Check that dependabot.yml exclude-paths covers every fixture root.
    Returns a list of missing paths (empty = all good).
    """
    content = DEPENDABOT_PATH.read_text(encoding="utf-8")
    missing = []
    for root in fixture_roots:
        rel = str(root.relative_to(REPO_ROOT))
        glob = f"{rel}/**"
        if glob not in content and rel not in content:
            missing.append(glob)
    return missing


def main() -> int:
    if not CONFIG_PATH.exists():
        print(f"error: {CONFIG_PATH} not found", file=sys.stderr)
        return 1

    with CONFIG_PATH.open("rb") as f:
        config = tomllib.load(f)

    raw_paths = config.get("fixture_dirs", {}).get("paths", [])
    fixture_roots = [REPO_ROOT / p for p in raw_paths]

    missing_roots = [r for r in fixture_roots if not r.exists()]
    if missing_roots:
        for r in missing_roots:
            print(f"warning: fixture dir does not exist: {r}", file=sys.stderr)

    print("osv-scanner configs:")
    written = write_osv_configs([r for r in fixture_roots if r.exists()])
    if not written:
        print("  (none — no lockfile directories found)")

    print("\ndependabot.yml validation:")
    missing = validate_dependabot(fixture_roots)
    if missing:
        print("  MISSING — add these to exclude-paths in .github/dependabot.yml:")
        for m in missing:
            print(f'    - "{m}"')
        return 1
    else:
        print("  ok — all fixture roots covered")

    return 0


if __name__ == "__main__":
    sys.exit(main())
