name: Auto-add to project

on:
  issues:
    types: [opened, transferred]
  pull_request_target:
    types: [opened]

jobs:
  add-to-project:
    name: Add to project board
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/gitrdunhq/projects/3
          github-token: ${{ secrets.GITRDUNHQ_PROJECT_BOT }}
